name: openvoice_env
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.9.79
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - expat=2.7.3
  - filelock=3.17.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - lcms2=2.16
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libexpat=2.7.3
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.50
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.18
  - pip=25.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.9.25
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2021.8.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.10.1
      - aiofiles==23.2.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - audioread==3.1.0
      - av==15.1.0
      - babel==2.17.0
      - bitarray==3.8.0
      - click==8.1.8
      - clip==1.0
      - cn2an==0.5.23
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - csvw==3.7.0
      - ctranslate2==4.6.2
      - cycler==0.12.1
      - cython==3.2.3
      - decorator==5.2.1
      - distro==1.9.0
      - dlinfo==2.0.0
      - dtw-python==1.7.2
      - einops==0.8.1
      - einops-exts==0.0.4
      - einx==0.3.0
      - eng-to-ipa==0.0.2
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - faster-whisper==1.2.1
      - ffmpy==1.0.0
      - flatbuffers==25.12.19
      - fonttools==4.60.2
      - frozendict==2.4.7
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - isodate==0.7.2
      - jieba==0.42.1
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - langid==1.1.6
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - munch==4.0.0
      - nltk==3.9.2
      - numba==0.60.0
      - onnxruntime==1.19.2
      - openai==2.14.0
      - openai-whisper==20250625
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - phonemizer==3.3.0
      - pillow==10.4.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - proces==0.1.7
      - protobuf==6.33.2
      - psutil==7.2.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pypinyin==0.55.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - rdflib==7.5.0
      - referencing==0.36.2
      - regex==2025.11.3
      - resampy==0.4.3
      - rfc3986==1.5.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - ruff==0.14.10
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - segments==2.3.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - starlette==0.49.3
      - sympy==1.13.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomlkit==0.12.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typeguard==4.4.4
      - typer==0.21.0
      - typer-slim==0.21.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - unidecode==1.4.0
      - uritemplate==4.2.0
      - uvicorn==0.39.0
      - vector-quantize-pytorch==1.27.15
      - wavmark==0.0.3
      - wcwidth==0.2.14
      - websockets==12.0
      - whisper-timestamped==1.15.9
      - zipp==3.23.0
prefix: C:\Users\perso\miniconda3\envs\openvoice_env
